### ISSUE TITLE
OpenPLC_Editor / PLCOpen_Editor

### ISSUE THREAD

**Issue by LumberJack013** [thiagoralves/OpenPLC_Editor#1]
Is OpenPLC_Editor an update of the PLCOpen_Editor you used to host in your website? Are both based on beremiz? Can you tell me the main differences between them?

**Comment by thiagoralves** [comment]
This is not an issue. This is a question that should've been asked on the forums: https://openplc.discussion.community/

PLCOpen Editor is the base common grounds between Beremiz and OpenPLC Editor. This new OpenPLC Editor brings interesting features from Beremiz (such as debugging support) but is constructed to be compatible with OpenPLC Runtime. As far as I know, it is not possible (at least not in an easy way) to generate a program for the OpenPLC Runtime using Beremiz.
