### ISSUE TITLE
TypeError when trying to place components in Ladder Logic program.

### ISSUE THREAD

**Issue by ClarentWielder** [thiagoralves/OpenPLC_Editor#101]
When trying to add components to a ladder logic diagram, I received a TypeError (see attached files). This occurred when I was trying to add a Left-Hand power rail and when I tried to add a contact.

I am running OpenPLC Editor using Ubuntu 22.04

Let me know if you have any questions, comments, or need more information.
[bug_report_2024_02_06__16-36-64.txt](https://github.com/thiagoralves/OpenPLC_Editor/files/14187672/bug_report_2024_02_06__16-36-64.txt)
[bug_report_2024_02_06__16-38-20.txt](https://github.com/thiagoralves/OpenPLC_Editor/files/14187674/bug_report_2024_02_06__16-38-20.txt)

**Comment by thiagoralves** [comment]
Use the supplied installer to install the editor in your system. It needs Python 3.9 and wxPython 4.2.0. You're running it on Python 3.10 and wxPython 4.2.1
