### ISSUE TITLE
Bug :(( (cant resimulate my projects)

### ISSUE THREAD

**Issue by JasperGraver** [thiagoralves/OpenPLC_Editor#133]
I made a little setup in OpenPLC Editor (the one in the yt vid) to learn a bit abt it and i clicked on start PLC Sim and then ran it and it ran fine then stopped the Sim and then tried starting it again and it gives me a bug report error thing i cant seem to find the bug report (im working on a laptop with limited privs so that may be a reason

maby someone else can try to remake the error

so in short
1. i made a little setup from the yt vid
2. started the PLC simulator
3. Clicked the debugging tool
4. stopped the PLC simulator
5. Tried starting the simulator again
6. error

![Screenshot 2024-10-07 090418](https://github.com/user-attachments/assets/4c36fff8-8047-423b-9556-7c50a32146dd)

Edit:
And yes i tried to search C:/Users/........
It says i dont have perms
In the console Log it says cleaning buildmap but it doesnt go any further then saying it :/

**Comment by JasperGraver** [comment]
And yes i tried to search C:/Users/........ 
It says i dont have perms

**Comment by JasperGraver** [comment]
In the console Log it says cleaning buildmap but it doesnt go any further then saying it :/

**Comment by JasperGraver** [comment]
@thiagoralves you have a solution for this?

**Comment by thiagoralves** [comment]
I can’t reproduce this. Make sure your antivirus or any other protection software is not blocking the debugger

**Comment by JasperGraver** [comment]
Temp fix = deleting the build map of the program everytime 
nothing is blocking the debugger it just cant delete/clean the buildmap

ill look into the blockers

**Comment by JasperGraver** [comment]
i didnt find anything else that would be able to block it from working ill just redownload the editor and i hope that fixes it and if it doesnt then ill just delete the build file everytime i wanna redo it

**Comment by thiagoralves** [comment]
The editor does delete the build folder every time you do a build, and that's most likely the action that is being blocked, perhaps by your Windows Defender, which is MS native antivirus on Windows. Try temporarily disabling Windows Defender during your compilation and simulation just to verify if the problem goes away. If it does, then certainly that's the culprit.

**Comment by JasperGraver** [comment]
Reinstalling seems to have fixed the problem thx for the help <3
