### ISSUE TITLE
Can't install on debian 11

### ISSUE THREAD

**Issue by Sirman13** [thiagoralves/OpenPLC_Editor#23]
E: Impossibile trovare il pacchetto python-wxgtk3.0
E: Impossibile trovare alcun pacchetto tramite il glob "python-wxgtk3.0"
E: Impossibile trovare alcun pacchetto tramite l'espressione regolare "python-wxgtk3.0"

**Comment by thiagoralves** [comment]
Debian 11 removed support for python-wxgtk3.0. It now only has wxgtk4.0 and that won't work with OpenPLC Editor. You can try to install wxgtk3.0 from debian 10 using a method similar to this: https://openplc.discussion.community/post/open-plc-editor-9298979?pid=1300091863 or you can just use Debian 10

**Comment by datamaskinen** [comment]
make an appimage of this when using packages not in main repositorys....

https://appimage.org/

**Comment by thiagoralves** [comment]
This issue was fixed by including wxgtk3.0 on the repository
