### ISSUE TITLE
python-wxgtk3.0 (flatpack?)

### ISSUE THREAD

**Issue by datamaskinen** [thiagoralves/OpenPLC_Editor#26]
new distros use python-wxgtk4.x... t

Traceback (most recent call last):
  File "Beremiz.py", line 33, in <module>
    import wx
ImportError: No module named wx

**Comment by datamaskinen** [comment]
a flatpack of openplc editor would be great

**Comment by jubnzv** [comment]
@datamaskinen I used to use [nix package manager](https://nixos.org/) when I was working with Beremiz. It has [a wxPython3 package](https://github.com/NixOS/nixpkgs/blob/master/pkgs/development/python-modules/wxPython/3.0.nix) which is compatible with both Beremiz and OpenPLC_Editor. So, you could consider this option too.

**Comment by datamaskinen** [comment]
aa ok tnx
