### ISSUE TITLE
where is the executable program?

### ISSUE THREAD

**Issue by 1934044624** [thiagoralves/OpenPLC_Editor#3]
Hello, founder, I want to know where are the executable programs . For example , I upload a file "Hello_world.st" ,  would it create a program "Hello_world" and where it would locate?

**Comment by thiagoralves** [comment]
/webserver/core/openplc

**Comment by 1934044624** [comment]
Thank you very much. It can run in raspberry pi now. Finally , if I have  ST,IL or C text  ，can it generate an executable program for omron plc?

**Comment by thiagoralves** [comment]
Of course not. You will have to use Omron software for that.
