### ISSUE TITLE
Support for Python3 

### ISSUE THREAD

**Issue by diplfranzhoepfinger** [thiagoralves/OpenPLC_Editor#40]
./install.sh installs a Python2.7 on Linux, even if Python 3 is available. 
would be nicer with Python 3, especially when using ESP-IDF.

**Comment by thiagoralves** [comment]
OpenPLC Editor does not run on Python 3, it needs Python 2. That's why the installer installs Python 2.7 on the system. Porting the editor to Python 3 is a long, ongoing effort. You can try the dev-python3 branch to check on the porting status. Right now it is still very buggy and not functional.

**Comment by franz-ms-muc** [comment]
any news on this ?

**Comment by thiagoralves** [comment]
Check the dev-python3 branch. The macOS release already uses that branch (since Python2 is not supported on mac anymore)
