### ISSUE TITLE
how to edit ModBUS & EtherCAT in OpenPLC_Editor

### ISSUE THREAD

**Issue by JinzeSi** [thiagoralves/OpenPLC_Editor#46]
We are working on a project that requires EtherCAT and Modbus for the softPLC, how do I use these in OpenPLC_editor?

**Comment by thiagoralves** [comment]
You don’t. Communication protocols are handled by the OpenPLC runtime, not the editor. Currently OpenPLC runtime supports Modbus (RTU and TCP). DNP3 and EtherNet/IP are also supported, but they are still experimental beta. Check the openplc website documentation for more info: https://openplcproject.com/docs/2-6-slave-devices/ and https://openplcproject.com/docs/2-5-modbus-addressing/
