### ISSUE TITLE
Issue with OpenPLC Editor installation on Ubuntu 18.04 Desktop

### ISSUE THREAD

**Issue by georgemakrakis** [thiagoralves/OpenPLC_Editor#7]
Hello,

I tried to install OpenPLC editor on my Ubuntu 18.04 desktop but when the install.sh script finishes and try to load the editor the Error window shows up and tells me to report you the bug that occurred.

[bug_report_2019_09_23__16-49-23.txt](https://github.com/thiagoralves/OpenPLC_Editor/files/3644482/bug_report_2019_09_23__16-49-23.txt)

**Comment by thiagoralves** [comment]
You're missing dependencies. Either you didn't run the installer or the installer failed to complete the installation of dependencies. Check for error messages after running the installer and fix the errors on your system.
