### ISSUE TITLE
FIXED MQTT_CONNECT_AUTH arduino error

### ISSUE THREAD

**Issue by duyle1402** [thiagoralves/OpenPLC_Editor#94]
/* At: OpenPLC\editor\arduino\src\lib\MQTT.h  line 302 */
` __GET_VAR(data__->BROKER).body[__GET_VAR(data__->BROKER).len] = '\0';`
`__GET_VAR(data__->BROKER).body[__GET_VAR(data__->USER).len] = '\0';`
`__GET_VAR(data__->BROKER).body[__GET_VAR(data__->PASSWORD).len] = '\0';`

/*Fix*/
` __GET_VAR(data__->BROKER).body[__GET_VAR(data__->BROKER).len] = '\0';`
`__GET_VAR(data__->USER).body[__GET_VAR(data__->USER).len] = '\0';`
`__GET_VAR(data__->PASSWORD).body[__GET_VAR(data__->PASSWORD).len] = '\0';`

**Comment by thiagoralves** [comment]
Nice catch! Fixing it now
